# Generated by Django 6.1.1 on 2026-10-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_DB',
            fields=[
                ('vehicle_type', models.TextField()),
                ('vehicle_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('owner_phone_no', models.IntegerField()),
                ('owner_address', models.TextField()),
                ('owner_name', models.CharField(max_length=11)),
                ('vehicle_brand', models.CharField(max_length=12)),
                ('owner_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
